---
version: "2.1"
services:
  jenkins:
    image: vortexict/jenkins_rv:0.3
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    restart: unless-stopped
volumes:
  jenkins_home:
  # docker.sock: